### PR TITLE
Minor additions to the menu

### PR DESCRIPTION
**Pull request by TenSeventy7**
Hewwo! The following commits add an additional "description" label to the recent/recommended section, although it shows the location rather than the modified/access time.

This also restores the background on the footer, albeit lighter.

Screenshot_20210703_123531

Change if necessary. :>

### CODE REVIEW

**Comment by prateekmedia** [comment]
Why you removed playAllGrid?

Also Why you Created separated files for ItemDocumentsView.

**Comment by prateekmedia** [comment]
Also can you see a white line b/w footer and body, yeah that's why I removed both Rectangle divider and background and instead added that in backgroundColor property.

**Comment by TenSeventy7** [comment]
`playAllGrid` only handles the "sliding to the left" animation the 'favorite' icons do when the menu is opened. I observed that Win11 doesn't have this animation behavior so I removed the whole `playAllGrid` portion.

`ItemGridDelegate`, which is a part of `ItemGridView`, also handles the list view on the All Apps portion of the menu. Since we might only want to put the secondary line on the recommended items list I just duplicated the views. Let me know if there's a better way of handling this.

I also noticed the same behavior even without the background, but I reverted the change.

**Comment by prateekmedia** [comment]
Done! Included your work in latest commits.

**Pull request closed without merging**
